Add option to save HTML content
crux-bphc/CMS-Scraper pull request #18
Opened 2023-03-11 06:10 UTC by soumitradev

Add optional arg `--html` to save HTML content as well

2023-03-11 07:10 UTC, abhijeetviswa commented on cmsscraper.py
> +            logger.info(f'Skipping file: {file_url}, Length={humanized_sizeof(file_size)}, exceeds {humanized_sizeof(MAX_DOWNLOAD_SIZE * 1024 * 1024)}')
This change has been introduced again in this commit.

2023-03-11 07:10 UTC, abhijeetviswa commented on cmsscraper.py
> +    sem = asyncio.Semaphore(SEMAPHORE_COUNT)
The idea behind the Semaphore was to limit number of async tasks making networking calls to Moodle. 
Since the HTML content (i.e string) is already in memory at this stage, a semaphore to limit the number of concurrent calls to `save_html_file` isn't required.

2023-03-11 08:15 UTC, soumitradev commented on cmsscraper.py
> +            logger.info(f'Skipping file: {file_url}, Length={humanized_sizeof(file_size)}, exceeds {humanized_sizeof(MAX_DOWNLOAD_SIZE * 1024 * 1024)}')
Removed the change in 95de62c

2023-03-11 08:19 UTC, soumitradev commented on cmsscraper.py
> +    sem = asyncio.Semaphore(SEMAPHORE_COUNT)
Removed the change in c0ef209

2023-03-13 06:05 UTC, abhijeetviswa requested changes

2023-03-13 06:05 UTC, abhijeetviswa commented on cmsscraper.py
> +        tasks.append(save_html_file(sem, *param))
What is sem here?

2023-03-13 06:05 UTC, abhijeetviswa commented on cmsscraper.py
> +    sem: asyncio.Semaphore,
Unused parameter

2023-03-18 16:38 UTC, soumitradev commented on cmsscraper.py
> +        tasks.append(save_html_file(sem, *param))
Supposed to be the semaphore the function uses. Since we removed the semaphore, I'll remove this too.

2023-03-18 16:43 UTC, soumitradev reviewed
Resolved in acc1cd3

2023-03-22 05:51 UTC, abhijeetviswa approved these changes

2023-03-26 14:12 UTC, merged